### ISSUE TITLE
TypeError: dest.on is not a function

### ISSUE THREAD

**Issue by maliyshock** [simeydotme/postcss-filter-mq#1]
**Error**
` TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (/home/denis/Desktop/experiment/company_test/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:516:8)
    at Gulp.<anonymous> (/home/denis/Desktop/experiment/company_test/Gulpfile.js:68:10)
    at module.exports (/home/denis/Desktop/experiment/company_test/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/denis/Desktop/experiment/company_test/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/denis/Desktop/experiment/company_test/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/denis/Desktop/experiment/company_test/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Gulpfile**
`gulp.task('filter-mq', function () {
    gulp.src(options.app + "css/index.css")
        .pipe( postcss([ filtermq ]) )
        .pipe( rename( "output.css" ) )
        .pipe( gulp.dest("dist/") );
})`

**Package.json**
`  "dependencies": {
    "bower": "^1.8.0",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-clean": "^0.3.2",
    "gulp-connect": "^5.0.0",
    "gulp-cssnano": "^2.1.2",
    "gulp-if": "^2.0.2",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.3.2",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-useref": "^3.1.2",
    "opn": "^4.0.2",
    "postcss": "^5.2.14",
    "postcss-filter-mq": "^1.0.1",
    "run-sequence": "^1.2.2",
    "wiredep": "^4.0.0",
    "yargs": "^6.6.0"
  },`

**Comment by maliyshock** [comment]
Need use gulp-postcss, not postcss

**Comment by savchukartur** [comment]
@maliyshock, здоровья тебе и счастья! помогла твоя подсказка
